from objects.Word import *

wordA : Word = Word([Elem("a", 2), Elem("b", 0), Elem("a", -1)])
wordB : Word = Word([Elem("a", 1)])
wordC : Word = word("a^2 b b^2 a^-1")

print(wordA)
print(wordA.reduced().word)
print(wordB.reduced().word)
print(wordB)
print(len(wordA.reduced().word), len(wordB.word))
print(Elem("A", 1) == Elem("A", 1))
print(wordA.reduced().strictEquality(wordB))
print(elem("a^2"))
print(wordC)
print(wordC.reduced())
print(wordC.reduced().inv())
k = wordC.reduced()
print(k.concat(k.inv()).reduced())
print(word("a").reduced())
